enum DashBoardPanelScreens {
  dashboard,
  company,
  news,
  movers,
  contactUs,
  newsCategories,
  insider,
  latestMover,
  notification,
  userReport,
  companyBulkUpload,
  latestMoversBulkUpload,
  newsCategoryBulkUpload,
  newsBulkUpload,
  moversBulkUpload,
  insiderBulkUpload,
}
